### PR TITLE
libvirt_qemu plugin: add import error handling

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
libvirt_qemu plugin: add import error handling

##### ISSUE TYPE

- Feature Pull Request

##### COMPONENT NAME
plugins/connection/libvirt_qemu.py

### CODE REVIEW

**Comment by Andersson007** [comment]
@felixfontein thanks for the hint:)

**Comment by Andersson007** [comment]
CC @odyssey4me 
FYI: I changed `authors` in galaxy.yml to let ansible-third-party check import the collection. Otherwise, the import fails with something like invalid collection metadata: authors cannot contain more than 64 characters

**Comment by Andersson007** [comment]
after this is merged, we can relaunch tests https://github.com/ansible-collections/community.libvirt/pull/57 and https://github.com/ansible-collections/community.libvirt/pull/58. They should pass

**Comment by Andersson007** [comment]
ready_for_review
FYI: whoever will merge this, please relaunch tests in https://github.com/ansible-collections/community.libvirt/pull/57 and https://github.com/ansible-collections/community.libvirt/pull/58 and if they are green, merge them as well, thanks

**Review by felixfontein — APPROVED** [review]

**Review by gundalow — APPROVED** [review]

**Comment by Andersson007** [comment]
@gundalow @felixfontein thanks for reviewing!

**Pull request merged**
