### PR TITLE
Fix/libvirt python

### LINKED ISSUE #86: Fix wrong requirement in the modules doc
##### SUMMARY
All the modules / plugins should be checked on the wrong requirement `python-libvirt` that should be changed to `libvirt-python` as was spotted in https://github.com/ansible-collections/community.libvirt/pull/56#discussion_r672973821

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
Please check all the modules / plugins

### PR DESCRIPTION
**Pull request by JensHeinrich**
##### SUMMARY
Fixes #86 

##### ISSUE TYPE
- Bugfix Pull Request
- Docs Pull Request

### CODE REVIEW

**Comment by Andersson007** [comment]
@JensHeinrich could you please [rebase](https://docs.ansible.com/ansible/latest/dev_guide/developing_rebasing.html) the PR?

**Comment by csmart** [comment]
Hi @JensHeinrich, thanks for this patch. Any chance you would be able to perform a rebase for us from main? If you need a hand, please let us know. Thanks!

**Comment by JensHeinrich** [comment]
Sorry, basically life happened

**Comment by csmart** [comment]
@JensHeinrich oh, no worries at all, been there many times myself :-) Thanks for the rebase!

**Comment by csmart** [comment]
@JensHeinrich it looks like having just `requirements` in a documentation fragment is not supported, however it does work if there is also `options`. I think we will need a fix to core in order to be able to merge this, so I'll look into that and keep this on hold for now. Once we get a fix into core then we can rebase this, CI should pass and we should be able to merge. Will let you know how I go. Thanks!

**Comment by csmart** [comment]
@JensHeinrich sorry for the delay. If you get a chance, would you mind doing another rebase and then adding an empty `options` dict into requirements.py? That seems to fix the docs problem for me (`ansible-doc -t connection community.libvirt.libvirt_qemu` renders correctly), and we can see if the pipelines are then happy. If you're too busy, let me know and I'll see if I can add it in for you and squash your commits down. Thanks!

```diff
diff --git a/plugins/doc_fragments/requirements.py b/plugins/doc_fragments/requirements.py
index 6d8b4ec..a181ed6 100644
--- a/plugins/doc_fragments/requirements.py
+++ b/plugins/doc_fragments/requirements.py
@@ -7,6 +7,7 @@ __metaclass__ = type
 
 class ModuleDocFragment(object):
     DOCUMENTATION = r"""
+options: {}
 requirements:
     - python >= 2.6
     - libvirt python bindings
```

**Comment by csmart** [comment]
Thanks @JensHeinrich, sorry I think we also need to do a rebase and to fix the conflict in the docs. Since your PR, [this change](https://github.com/ansible-collections/community.libvirt/commit/c931c5865210a2a17178c31db17357214d3e6807) has landed which replaces `ansible_executable` with `ansible_shell_type`. Any chance you could do a rebase and fix up that, then do another force push? Cheers!

**Comment by csmart** [comment]
Thanks @JensHeinrich!

**Comment by csmart** [comment]
Sorry @JensHeinrich, could I bother you for one last rebase?... then I think we're ready to merge this in.

**Comment by csmart** [comment]
@JensHeinrich  thank you so much for your contribution here and your persistence to get this in for us. Much appreciated!

**Comment by Andersson007** [comment]
@JensHeinrich thanks for the PR! @csmart thanks for reviewing!

**Pull request merged**
