### PR TITLE
Drop redundant LICENSE file

### LINKED ISSUE #122: Is it really necessary to include both COPYING and LICENSE?
##### SUMMARY
The collection includes both COPYING and LICENSE files, which are almost identical apart from whitespace and use of https:// URLs in LICENSE vs. http:// URLs in COPYING. Perhaps one could be removed? My suggestion would be to copy the contents of the (apparently more up to date) LICENSE file into the COPYING file and then get rid of the LICENSE file, since the COPYING file is referenced elsewhere in the collection.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
COPYING, LICENSE

##### ANSIBLE VERSION

```paste below
ansible [core 2.12.5]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/paul/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.10/site-packages/ansible
  ansible collection location = /home/paul/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.4 (main, Mar 25 2022, 00:00:00) [GCC 11.2.1 20220127 (Red Hat 11.2.1-9)]
  jinja version = 3.0.1
  libyaml = True
```
(not that it matters)

### PR DESCRIPTION
**Pull request by pghmcfc**
##### SUMMARY
Remove the redundant LICENSE file, which is basically the same as the COPYING file. The COPYING file is referenced elsewhere in the code/documentation, so that's the one to keep. Fixes #122.

##### ISSUE TYPE
- Docs Pull Request

##### COMPONENT NAME
COPYING, LICENSE.

##### ADDITIONAL INFORMATION
The LICENSE file appeared to be slightly more up to date than the COPYING file (e.g. https:// URLs rather than http:// URLs), so the COPYING file is updated to have the same content as the original LICENSE file.

### CODE REVIEW

**Review by Andersson007 — APPROVED** [review]
LGTM

**Comment by Andersson007** [comment]
cc @csmart

**Comment by csmart** [comment]
Thanks @pghmcfc!

**Comment by Andersson007** [comment]
@pghmcfc thanks for the contribution!
@csmart thanks for reviewing and merging!

**Comment by csmart** [comment]
@Andersson007 thanks to you for reviewing, too 👍

**Pull request merged**
