### PR TITLE
Release 1.2.0 commit

### PR DESCRIPTION
**Pull request by csmart**
##### SUMMARY

New release 1.2.0

### CODE REVIEW

**Comment by csmart** [comment]
As per https://github.com/ansible-collections/community.libvirt/issues/81#issuecomment-1201080903

**Comment by Andersson007** [comment]
@csmart there's a strange mismatch between the changelog and tags

**Comment by csmart** [comment]
@Andersson007 thank you! Yes, I pushed the wrong branch...

**Review by Andersson007 — APPROVED** [review]
LGTM now:) Thanks

**Pull request merged**
